print("Content-type:text/html\r\n\r\n")
print('<html>')
print('<head>')
print('<title> First CGI Program')
print('</title>')
print('</head>')
print('<body>')
print('<h1> Hi Pooja </h1>')
print('</body>')
print('</html>')